import "./globals.css";
import { Inter, Fraunces } from "next/font/google";
import { baseMetadata, orgJsonLd, websiteJsonLd } from "@/lib/seo";
import { ServiceWorkerRegistrar } from "@/components/ServiceWorkerRegistrar";
import { OfflineStatus } from "@/components/OfflineStatus";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});
const fraunces = Fraunces({
  subsets: ["latin"],
  variable: "--font-display",
  display: "swap",
  weight: ["600", "700", "800"],
});

// Favicon set is auto-wired by Next.js from:
//   app/favicon.ico        — legacy fallback (16/32/48 bundled)
//   app/icon.svg           — modern browsers
//   app/apple-icon.png     — iOS home-screen tile
// All three are generated by `npm run icons` from the canonical
// public/icons/icon.svg (the user-supplied brand mark). We keep
// baseMetadata simple so the conventions stay one source of truth.
export const metadata = baseMetadata;

export const viewport = {
  themeColor: "#fbf7ef",
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="es"
      className={`${inter.variable} ${fraunces.variable} h-full antialiased`}
    >
      <head>
        <link rel="manifest" href="/manifest.json" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(orgJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }}
        />
      </head>
      <body className="flex min-h-full flex-col">
        {children}
        <ServiceWorkerRegistrar />
        <OfflineStatus />
      </body>
    </html>
  );
}
