// Audio manifest for "say this" rights scripts.
// Generated by scripts/generate-audio.mjs from lib/content.ts.
// Treat as source of truth at runtime; never edit by hand mid-section.
import type { Locale } from "./i18n";

export type AudioClip = {
  url: string;
  durationMs: number;
  bytes: number;
  voice: string;
  transcript: string;
};

export type AudioManifest = {
  generatedAt: string;
  source: "macos-say" | "elevenlabs" | "human" | "mixed";
  steps: Record<string, Partial<Record<Locale, AudioClip>>>;
  fullNarration?: Partial<Record<string, Partial<Record<Locale, AudioClip>>>>;
};

import manifest from "@/public/audio/manifest.json" with { type: "json" };

// `manifest.json` is regenerated by `npm run audio` and loaded as a static
// asset at build time. The file is committed so static prerendering and the
// service worker precache can both see deterministic URLs.
export const audioManifest = manifest as unknown as AudioManifest;

export function clipKey(slug: string, stepIndex: number): string {
  return `${slug}:${stepIndex}`;
}

export function getStepClip(
  slug: string,
  stepIndex: number,
  locale: Locale
): AudioClip | null {
  const entry = audioManifest.steps[clipKey(slug, stepIndex)];
  return entry?.[locale] ?? null;
}

export function isAudioPwaCachingEnabled(): boolean {
  return process.env.NEXT_PUBLIC_PWA_AUDIO === "1";
}

export function allClipUrls(): string[] {
  const urls: string[] = [];
  for (const entry of Object.values(audioManifest.steps)) {
    if (entry?.en) urls.push(entry.en.url);
    if (entry?.es) urls.push(entry.es.url);
  }
  for (const entry of Object.values(audioManifest.fullNarration ?? {})) {
    if (entry?.en) urls.push(entry.en.url);
    if (entry?.es) urls.push(entry.es.url);
  }
  return urls;
}

export function hasAudioForGuide(slug: string, locale: Locale): boolean {
  const prefix = `${slug}:`;
  for (const key of Object.keys(audioManifest.steps)) {
    if (!key.startsWith(prefix)) continue;
    const entry = audioManifest.steps[key];
    if (entry && entry[locale]) return true;
  }
  return false;
}
