-- Phase 9 seed: the 8 starter rows previously hardcoded in lib/resources.ts.
-- Idempotent via ON CONFLICT (id) DO NOTHING.

insert into public.resources
  (id, name, category, city, state, phone, website, languages, cost,
   emergency, notes_en, notes_es, verified_by, verified_at, published)
values
  ('aclu-national','ACLU – Know Your Rights','legal',null,null,null,
   'https://www.aclu.org/know-your-rights/',
   '{"English","Español"}','free',false,
   'National civil liberties information and Know Your Rights guides.',
   'Información nacional de derechos civiles y guías Conoce Tus Derechos.',
   'seed', now(), true),
  ('ilrc','Immigrant Legal Resource Center (ILRC)','legal','San Francisco','CA',null,
   'https://www.ilrc.org/',
   '{"English","Español"}','free',false,
   'Educational resources for immigrants and legal advocates.',
   'Recursos educativos para inmigrantes y defensores legales.',
   'seed', now(), true),
  ('uwd-hotline','United We Dream — MigraWatch Hotline','hotline',null,null,'1-844-363-1423',
   'https://unitedwedream.org/',
   '{"English","Español"}','free',true,
   'Report ICE activity and get connected to support (volunteer-run).',
   'Reporta actividad de ICE y conéctate con apoyo (voluntarios).',
   'seed', now(), true),
  ('211','211 — Local Help Line','hotline',null,null,'211',
   'https://www.211.org/',
   '{"English","Español"}','free',true,
   'Dial 211 to connect to local food, housing, and health resources.',
   'Marca 211 para conectarte con recursos locales de comida, vivienda y salud.',
   'seed', now(), true),
  ('fqhc-finder','Find a Community Health Center','clinic',null,null,null,
   'https://findahealthcenter.hrsa.gov/',
   '{"English","Español"}','sliding',false,
   'Federal directory of community health centers serving everyone.',
   'Directorio federal de clínicas comunitarias que atienden a todos.',
   'seed', now(), true),
  ('consulado-mx','Consulado de México (US Network)','consulate',null,null,null,
   'https://consulmex.sre.gob.mx/',
   '{"Español"}','varies',false,
   'Mexican consular protection services across the U.S.',
   'Servicios de protección consular mexicana en EE. UU.',
   'seed', now(), true),
  ('feeding-america','Feeding America — Find a Food Bank','food',null,null,null,
   'https://www.feedingamerica.org/find-your-local-foodbank',
   '{"English","Español"}','free',false,
   'Locator for food banks near you.',
   'Localizador de bancos de alimentos cerca de ti.',
   'seed', now(), true),
  ('domestic-violence-hotline','National Domestic Violence Hotline','hotline',null,null,'1-800-799-7233',
   'https://www.thehotline.org/',
   '{"English","Español"}','free',true,
   '24/7 confidential support.',
   'Apoyo confidencial las 24 horas.',
   'seed', now(), true)
on conflict (id) do nothing;
